### ISSUE TITLE
It is not immediately visible that the 1 is encumbrance, plase use qualified prameter name or write the comment

### ISSUE THREAD

**Issue by janisolekss** [kid101/EncumbranceDemo#2]
https://github.com/kid101/EncumbranceDemo/blob/26cea3c367ac608e358ca7f6f141378706aa400b/encumbrance-bakery/src/main/java/net/corda/demo/bakery/SellCakeInitiator.java#L88

**Comment by kid101** [comment]
Thanks, Janis. have provided a comment to make it more evident.
